# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\msys64\mingw64\bin\cmake.exe

# The command to remove a file.
RM = D:\msys64\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Francy\Desktop\Main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Francy\Desktop\Main\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	D:\msys64\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	D:\msys64\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Francy\Desktop\Main\build\CMakeFiles C:\Users\Francy\Desktop\Main\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Francy\Desktop\Main\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AIGameDevSimulator

# Build rule for target.
AIGameDevSimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 AIGameDevSimulator
.PHONY : AIGameDevSimulator

# fast build rule for target.
AIGameDevSimulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/build
.PHONY : AIGameDevSimulator/fast

GameProject/Main.obj: GameProject/Main.cpp.obj
.PHONY : GameProject/Main.obj

# target to build an object file
GameProject/Main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/GameProject/Main.cpp.obj
.PHONY : GameProject/Main.cpp.obj

GameProject/Main.i: GameProject/Main.cpp.i
.PHONY : GameProject/Main.i

# target to preprocess a source file
GameProject/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/GameProject/Main.cpp.i
.PHONY : GameProject/Main.cpp.i

GameProject/Main.s: GameProject/Main.cpp.s
.PHONY : GameProject/Main.s

# target to generate assembly for a file
GameProject/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/GameProject/Main.cpp.s
.PHONY : GameProject/Main.cpp.s

imgui/backends/imgui_impl_glfw.obj: imgui/backends/imgui_impl_glfw.cpp.obj
.PHONY : imgui/backends/imgui_impl_glfw.obj

# target to build an object file
imgui/backends/imgui_impl_glfw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/backends/imgui_impl_glfw.cpp.obj
.PHONY : imgui/backends/imgui_impl_glfw.cpp.obj

imgui/backends/imgui_impl_glfw.i: imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui/backends/imgui_impl_glfw.cpp.i

imgui/backends/imgui_impl_glfw.s: imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui/backends/imgui_impl_glfw.cpp.s

imgui/backends/imgui_impl_opengl3.obj: imgui/backends/imgui_impl_opengl3.cpp.obj
.PHONY : imgui/backends/imgui_impl_opengl3.obj

# target to build an object file
imgui/backends/imgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/backends/imgui_impl_opengl3.cpp.obj
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.obj

imgui/backends/imgui_impl_opengl3.i: imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.i

imgui/backends/imgui_impl_opengl3.s: imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.s

imgui/imgui.obj: imgui/imgui.cpp.obj
.PHONY : imgui/imgui.obj

# target to build an object file
imgui/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui.cpp.obj
.PHONY : imgui/imgui.cpp.obj

imgui/imgui.i: imgui/imgui.cpp.i
.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s
.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_demo.obj: imgui/imgui_demo.cpp.obj
.PHONY : imgui/imgui_demo.obj

# target to build an object file
imgui/imgui_demo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui_demo.cpp.obj
.PHONY : imgui/imgui_demo.cpp.obj

imgui/imgui_demo.i: imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.i

# target to preprocess a source file
imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.cpp.i

imgui/imgui_demo.s: imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.s

# target to generate assembly for a file
imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.cpp.s

imgui/imgui_draw.obj: imgui/imgui_draw.cpp.obj
.PHONY : imgui/imgui_draw.obj

# target to build an object file
imgui/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui_draw.cpp.obj
.PHONY : imgui/imgui_draw.cpp.obj

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_tables.obj: imgui/imgui_tables.cpp.obj
.PHONY : imgui/imgui_tables.obj

# target to build an object file
imgui/imgui_tables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui_tables.cpp.obj
.PHONY : imgui/imgui_tables.cpp.obj

imgui/imgui_tables.i: imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.i

# target to preprocess a source file
imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.cpp.i

imgui/imgui_tables.s: imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.s

# target to generate assembly for a file
imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.cpp.s

imgui/imgui_widgets.obj: imgui/imgui_widgets.cpp.obj
.PHONY : imgui/imgui_widgets.obj

# target to build an object file
imgui/imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui_widgets.cpp.obj
.PHONY : imgui/imgui_widgets.cpp.obj

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AIGameDevSimulator.dir\build.make CMakeFiles/AIGameDevSimulator.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... AIGameDevSimulator
	@echo ... GameProject/Main.obj
	@echo ... GameProject/Main.i
	@echo ... GameProject/Main.s
	@echo ... imgui/backends/imgui_impl_glfw.obj
	@echo ... imgui/backends/imgui_impl_glfw.i
	@echo ... imgui/backends/imgui_impl_glfw.s
	@echo ... imgui/backends/imgui_impl_opengl3.obj
	@echo ... imgui/backends/imgui_impl_opengl3.i
	@echo ... imgui/backends/imgui_impl_opengl3.s
	@echo ... imgui/imgui.obj
	@echo ... imgui/imgui.i
	@echo ... imgui/imgui.s
	@echo ... imgui/imgui_demo.obj
	@echo ... imgui/imgui_demo.i
	@echo ... imgui/imgui_demo.s
	@echo ... imgui/imgui_draw.obj
	@echo ... imgui/imgui_draw.i
	@echo ... imgui/imgui_draw.s
	@echo ... imgui/imgui_tables.obj
	@echo ... imgui/imgui_tables.i
	@echo ... imgui/imgui_tables.s
	@echo ... imgui/imgui_widgets.obj
	@echo ... imgui/imgui_widgets.i
	@echo ... imgui/imgui_widgets.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

